# Generated by Django 4.2.5 on 2023-09-25 12:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('term', '0004_alter_term_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='term',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 15, 13, 3, 855588)),
        ),
    ]
