# Generated by Django 4.2.5 on 2023-11-09 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0009_alter_term_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 29, 17, 934317)),
        ),
    ]
