# Generated by Django 4.2.5 on 2023-11-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehelper', '0012_alter_onlinehelper_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinehelper',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onlinehelper',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 16, 38, 8, 798585)),
        ),
    ]
