# Generated by Django 4.2.5 on 2023-11-17 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehelper', '0013_onlinehelper_slug_alter_onlinehelper_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinehelper',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 17, 8, 21, 168994)),
        ),
        migrations.AlterField(
            model_name='onlinehelper',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
