# Generated by Django 4.2.5 on 2023-11-17 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehelper', '0014_alter_onlinehelper_cdate_alter_onlinehelper_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinehelper',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 17, 56, 24, 917977)),
        ),
    ]
