# Generated by Django 4.2.5 on 2023-11-09 13:29

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 29, 17, 938717))),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
