# Generated by Django 4.2.5 on 2023-11-09 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='ancore',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='help',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 51, 53, 551127)),
        ),
    ]
