# Generated by Django 4.2.5 on 2023-11-09 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_help_ancore_alter_help_cdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='ancore',
            new_name='anchor',
        ),
        migrations.AlterField(
            model_name='help',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 15, 54, 1, 42822)),
        ),
    ]
