# Generated by Django 4.2.5 on 2023-11-17 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_alter_help_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 22, 8, 41, 525293)),
        ),
    ]
