# Generated by Django 4.2.3 on 2023-09-08 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 10, 0, 54, 647633)),
        ),
    ]
