# Generated by Django 4.2.5 on 2023-09-22 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 18, 55, 51, 633481)),
        ),
    ]
