# Generated by Django 4.2.5 on 2023-11-17 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 16, 19, 18, 99860)),
        ),
    ]
