# Generated by Django 4.2.5 on 2023-11-17 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_article_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 21, 1, 38, 364709)),
        ),
    ]
