# Generated by Django 4.2.5 on 2023-09-08 05:24

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_detail', models.CharField(blank=True, max_length=100)),
                ('cdate', models.DateTimeField(default=datetime.datetime(2023, 9, 8, 8, 24, 54, 339415))),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('sources', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
