# Generated by Django 4.2.5 on 2023-11-07 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0008_alter_lection_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 13, 47, 4, 799823)),
        ),
    ]
