# Generated by Django 4.2.5 on 2023-11-17 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0016_alter_lection_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lection',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 21, 13, 15, 536092)),
        ),
    ]
